export const mockProperties = [
  {
    id: 1,
    title: "Modern Downtown Apartment",
    price: 850000,
    rentFrequency: "yearly",
    rooms: 2,
    baths: 2,
    area: 1200,
    coverPhoto: { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400" },
    location: [{ name: "Dubai Marina" }, { name: "Dubai" }],
    agency: { name: "Premium Realty" },
    isVerified: true,
    purpose: "for-rent",
  },
  {
    id: 2,
    title: "Luxury Villa with Pool",
    price: 2500000,
    rentFrequency: "yearly",
    rooms: 4,
    baths: 3,
    area: 3500,
    coverPhoto: { url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400" },
    location: [{ name: "Palm Jumeirah" }, { name: "Dubai" }],
    agency: { name: "Elite Homes" },
    isVerified: true,
    purpose: "for-sale",
  },
  {
    id: 3,
    title: "Cozy Studio Near Metro",
    price: 45000,
    rentFrequency: "yearly",
    rooms: 1,
    baths: 1,
    area: 650,
    coverPhoto: { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400" },
    location: [{ name: "Business Bay" }, { name: "Dubai" }],
    agency: { name: "City Living" },
    isVerified: false,
    purpose: "for-rent",
  },
  {
    id: 4,
    title: "Family Townhouse",
    price: 1800000,
    rentFrequency: "yearly",
    rooms: 3,
    baths: 2,
    area: 2200,
    coverPhoto: { url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400" },
    location: [{ name: "Arabian Ranches" }, { name: "Dubai" }],
    agency: { name: "Family Homes" },
    isVerified: true,
    purpose: "for-sale",
  },
];
